spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090